<?php

use PHPUnit\Framework\TestCase;
include_once "../Collection.php";
include_once "../Document.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-02-02 at 01:05:10.
 */
class CollectionTest extends TestCase {

    /**
     * @var Collection
     */
    protected $dbConnection;
    protected $host = '192.168.56.101';
    protected $user = 'Christine Mahler';
    protected $password = 'aurora83';
    protected $database = 'collection';
    protected $collection;
    protected $addDocument;
    protected $deleteDocument;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->dbConnection = new DBConnection($this->host, $this->user, $this->password, $this->database);
        $this->object = new Collection($this->dbConnection);
        $this->addDocument = new Document('White Paper', 'Test Title', 'DOCX', '150 MB', '2019-01-26');
        $this->deleteDocument = new Document('Assignment', 'Not Test Title', 'XSLX', '250 MB', '2019-01-25');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        unset($this->dbConnection);
        unset($this->collection);
    }

    /**
     * @covers Collection::getDocumentsByUser
     * @todo   Implement testGetDocuments().
     */
    public function testGetDocuments() {
        $count = count($this->object->getDocuments());
        $this->assertEquals(count($this->object->getDocuments()), $count);
    }

    /**
     * @covers Collection::addDocument
     * @todo   Implement testAddDocument().
     */
    public function testAddDocument() {
        $count = count($this->object->getDocuments());
        $this->object->addDocument($this->addDocument);
        $this->assertEquals(count($this->object->getDocuments($this->user)), $count+1);
    }

    /**
     * @covers Collection::deleteDocument
     * @depends testAddDocument
     */
    public function testDeleteDocument() {
        $count = count($this->object->getDocuments());
        
        $this->object->deleteDocument($this->deleteDocument);
        $this->assertEquals(count($this->object->getDocuments()), $count);
        
        $this->object->deleteDocument($this->addDocument);
        $this->assertEquals(count($this->object->getDocuments()), $count-1);
    }

}
